from django.urls import path
import Admin.views as admin_views

urlpatterns = [
    path('AdminPage', admin_views.AdminPage, name='AdminPage'),
    path('admin_login', admin_views.admin_login, name='admin_login'),
    path('check_admin', admin_views.check_admin, name='check_admin'),
    path('show_ad', admin_views.show_ad, name='show_ad'),
    path('admin_view_ad', admin_views.admin_view_ad, name='admin_view_ad'),
    path('approve_ad', admin_views.approve_ad, name='approve_ad'),
    path('show_report', admin_views.show_report, name='show_report'),
    path('open_report', admin_views.open_report, name='open_report'),
    path('discard_ad', admin_views.discard_ad, name='discard_ad'),
    path('discard_report', admin_views.discard_report, name='discard_report'),
    path('discard_report_ad', admin_views.discard_report_ad, name='discard_report_ad'),
    path('remove_post_ad', admin_views.remove_post_ad, name='remove_post_ad'),
    path('remove_ad', admin_views.remove_ad, name='remove_ad'),
    path('update_post_type', admin_views.update_post_type, name='update_post_type'),
    path('Promote_ad', admin_views.Promote_ad, name='Promote_ad'),
    path('discard_promote_request', admin_views.discard_promote_request, name='discard_promote_request'),
    path('make_member', admin_views.make_member, name='make_member'),
    path('approve_membership', admin_views.approve_membership, name='approve_membership'),
    path('discard_membership', admin_views.discard_membership, name='discard_membership'),
    path('add_loc_cat', admin_views.add_loc_cat, name='add_loc_cat'),
    path('add_new_loc', admin_views.add_new_loc, name='add_new_loc'),
    path('add_new_subloc', admin_views.add_new_subloc, name='add_new_subloc'),
    path('add_new_cat', admin_views.add_new_cat, name='add_new_cat'),
    path('add_new_subcat', admin_views.add_new_subcat, name='add_new_subcat'),
    path('delete_expired_ads', admin_views.delete_expired_ads, name='delete_expired_ads'),
    path('all_members', admin_views.all_members, name='all_members'),
    path('delete_all_expired_members', admin_views.delete_all_expired_members, name='delete_all_expired_members'),
    path('make_admin', admin_views.make_admin, name='make_admin'),
    path('register_admin', admin_views.register_admin, name='register_admin'),
]
